steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/zap-mas-451218/datagotchi-backend:prod-$COMMIT_SHA",
        ".",
      ]
    dir: "back"

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/zap-mas-451218/datagotchi-backend:prod-$COMMIT_SHA"]

  # Deploy to production environment
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "datagotchi-backend-prod"
      - "--image=gcr.io/zap-mas-451218/datagotchi-backend:prod-$COMMIT_SHA"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--port=8080"
      - "--memory=2Gi"
      - "--cpu=2"
      - "--max-instances=10"
      - "--min-instances=1"
      - "--timeout=300"
      - "--set-env-vars=ENVIRONMENT=production,APP_ENV=production"

images:
  - "gcr.io/zap-mas-451218/datagotchi-backend:prod-$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
